@startuml
database "HANA" {
  folder "SBODEMOUS" {
	[OITM]
  }
  frame "COMPANY DB" {
	[OCLG]
  }
}

cloud {
  ServiceLayer - [SAP B1]
  [SAP B1] .u.> [OITM]
}
package "model" {
  [User]
}
package "b1s" {
  [LoginDataSource] - ILoginDS
  [LoginDataSource] ..> ServiceLayer
  [LoginDataSource] ..> [User]
  [Repository] ..> [LoginDataSource]
  [Repository] - getLoginDS
  getLoginDS ..> ILoginDS
}
package "vm" {
  [AppViewModel] - ILoginVM
  [AppViewModel] ..> [User]
  [AppViewModel] ..> getLoginDS
  [ViewModelFactory] - getLoginVM
  [ViewModelFactory] ..>[AppViewModel]
  getLoginVM ..> ILoginVM
}
package "app" {
  [LoginActivity] ..> [User]
  [LoginActivity] .u.> [ILoginVM]
  [LoginActivity] .u.> [getLoginVM]
  [MainActivity]
}

@enduml